version: '3.9'
services:
  db:
    container_name: db_postgres 
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2137:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  postgres-db:
    driver: local

