// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBL_PoC_Api.Persistance;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NBL_PoC_Api.Migrations.Todo
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("todos")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NBL_PoC_Api.Todos.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Todos", "todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test_desc_1",
                            IsCompleted = true,
                            Title = "Test_title_1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test_desc_2",
                            IsCompleted = false,
                            Title = "Test_title_2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test_desc_3",
                            IsCompleted = true,
                            Title = "Test_title_3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test_desc_4",
                            IsCompleted = false,
                            Title = "Test_title_4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Test_desc_5",
                            IsCompleted = false,
                            Title = "Test_title_5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
